### ISSUE TITLE
Unable to reach online documents or use Better With Mods Manual

### ISSUE THREAD

**Issue by geech** [BetterWithMods/BetterWithMods#1017]
The online documents returns a 404 and the Better With Mods Manual returns a "Document not Found: en_us/index.md" error.  Reporting per error.  See Screenshot.

Playing SevTech Ages 3.0.7 modpack

![capture](https://user-images.githubusercontent.com/2355244/41214073-c3f1fbbe-6d38-11e8-8ed0-df91dd1e6201.PNG)
Better With Mods is transitioning to use https://gitlab.com/BetterWithMods/BetterWithMods, please submit issues there instead.

**Comment by Madxmike** [comment]
Already fixed
