### ISSUE TITLE
Rustic Integration not honoring HCLumber setting

### ISSUE THREAD

**Issue by TensorTime** [BetterWithMods/BetterWithMods#553]
On 1.12 when I put nothing but the two mods in with HCLumber set to true only minecraft based trees seem to break into bark and dust.  So break a tree get a logWood (for instance ironwood).  It still crafts into an oak chopping block and you can still place the logs on the block and properly get planks.  

So basically if I want HCLumber I can't have Rustic or it allows for a workaround by searching for Rustic trees.  I haven't seen this same issue with Forestry when I tested.  Though I have had issues placing forestry logs onto the chopping block as well.  That is more of an annoyance since it doesn't provide a workaround.

**Comment by primetoxinz** [comment]
Fixed
