### ISSUE TITLE
ModTweaker Anvil Shaped with holes

### ISSUE THREAD

**Issue by whimsky** [BetterWithMods/BetterWithMods#563]
The ability to add a script via ModTweaker to the Anvil is limited.
Only Recipes [row x column] (1x4), (2x4), (3x4), (4x4) can be made if they're solid.   [solid meaning I can't make something like a ladder because it has two holes in the recipe]  I'm also unable to make anything less than 4 items wide.
Using "null" or <minecraft:air> returns errors.

mods.betterwithmods.Anvil.addShaped(<minecraft:dirt>, [
   [<minecraft:stone>,<minecraft:stone>,<minecraft:stone>,<minecraft:stone>],
   [<minecraft:stone>,null,null,<minecraft:stone>],
   [<minecraft:stone>,<minecraft:stone>,<minecraft:stone>,<minecraft:stone>]
]);
https://imgur.com/a/whHqy

mods.betterwithmods.Anvil.addShaped(<minecraft:dirt>, [
   [<minecraft:stone>,<minecraft:stone>,<minecraft:stone>,<minecraft:stone>],
   [<minecraft:stone>,<minecraft:air>,<minecraft:air>,<minecraft:stone>],
   [<minecraft:stone>,<minecraft:stone>,<minecraft:stone>,<minecraft:stone>]
]);
https://cdn.discordapp.com/attachments/337734764461162498/355480395632082954/unknown.png

**Comment by primetoxinz** [comment]
I think we fixed this a long time ago, I don't remember
