### ISSUE TITLE
Milking Cows

### ISSUE THREAD

**Issue by vivagabe** [BetterWithMods/BetterWithMods#570]
Is there anyway to limit the amount of times you can milk a cow?  Seems kind of cheap to be able to milk without limit.

EDIT: BtW has the udder mechanic..not sure if something like that would be possible.

**Comment by primetoxinz** [comment]
I attempted this a couple weeks ago but ran into some issues with getting it exactly how I wanted it. I might add a half functional version and then slowly get it to be exactly like in BTW

**Comment by vivagabe** [comment]
Oh cool.  I look forward to that.

**Comment by primetoxinz** [comment]
Moved to Projects tab
