### ISSUE TITLE
Fat not working as described

### ISSUE THREAD

**Issue by kiwifrogg** [BetterWithMods/BetterWithMods#594]
In the config and wiki it says fat drains before hunger, however its not working like that, fully fed with 5 fat, hunger drains to 1 hunch so I'm famished and unable to jump, yet the fat does not move. If I then eat the fat drops to the new hunger point.  Also is there a way to disable or even lower the no jump effect when really hungry.

**Comment by primetoxinz** [comment]
If you are on 1.12 please update as this has been fixed.

**Comment by kiwifrogg** [comment]
This was in version 1.12-2.0.14, that is the newest one as far as I can tell.

**Comment by Timeslice42** [comment]
@kiwifrogg Can this be closed now?
