### ISSUE TITLE
List of compatible mods?

### ISSUE THREAD

**Issue by Xorbah** [BetterWithMods/BetterWithMods#595]
Hey. Sorry, I know this isn't an issue but is there a cited list of mods compatible with BTM anywhere? (Other than Better With Addons)

**Comment by primetoxinz** [comment]
The best source would be reading the config file, any specific config on our end in visible in there. I don't know of any other mod that adds compat for BWM

**Comment by DaedalusGame** [comment]
Debarked Logs lmao
