### ISSUE TITLE
[Feature Request] Configurable Sidings, Mouldings and Corners

### ISSUE THREAD

**Issue by Ghost8909** [BetterWithMods/BetterWithMods#597]
I love the Saw and what it does to blocks. I love the new blocks it makes. However, I was wondering if it would be possible to add a section to the config where one could input block ids from other mods, and this one would generate Sidings, Mouldings, and Corners based on those blocks?

The user would be required to enter the id, such as "quark:vertical_planks:0", and define it as wood, in this case, or stone. Then BWMs would generate a set of Sidings, Mouldings and Corners for Quark's Vertical Oak Planks.

Alternatively, the mod could have an optional config where it would automatically generate them for anything forge recognizes as wood or stone blocks, in a method similar to how Forge Ore Dictionary recognizes ore, ingots, etc?

**Comment by primetoxinz** [comment]
As of the moment this is more or less impossible, I definitely want it to happen but if it did it would delete all existing Sidings, Mouldings and Corners. 
It's in consideration :)

**Comment by primetoxinz** [comment]
Gonna close this as it probably won't happen for a long time
