### ISSUE TITLE
Crash when clicking on stump with non-vanilla tool

### ISSUE THREAD

**Issue by Lyneira** [BetterWithMods/BetterWithMods#598]
I have HCStumping enabled, when clicking on a tree stump with a non-vanilla tool (Copper Axe from Thermal Foundation in this case), the game crashes. Crash report:

[crash-2017-10-12_09.48.12-client.txt](https://github.com/BetterWithMods/BetterWithMods/files/1378536/crash-2017-10-12_09.48.12-client.txt)

If I disable HCStumping, the game no longer crashes.

**Comment by BeetoGuy** [comment]
Possibly fixed, will have to load a test instance with Thermal Foundation in the morning.

**Comment by Lyneira** [comment]
I've added ActuallyAdditions and TinkersConstruct to my instance for testing and also tried with the the axes from those two mods, they work fine as well with HCStumping enabled, so it does look like there's something strange going on with the Thermal Foundation tools.
