### ISSUE TITLE
Hardcore Hunger ignores Natural Health Regeneration False

### ISSUE THREAD

**Issue by Krhymez** [BetterWithMods/BetterWithMods#603]
I am using Hardcore hunger enabled in the pack i am making.
My issue is that when this is enabled, it also overrides Natural health regeneration. (it enables it)

In the pack, i have regeneration disabled with a healing mod, which requires players to use medical supplies to regain lost health. Currently this is not working. If i have hardcore hunger enabled and i stand still, my health regenerates naturally.

Any chance you can add a config like to hardcore hunger to also disable natural health regeneration.

Thank you.

**Comment by Krhymez** [comment]
This issue was closed, does that mean it is fixed? or is it not considered an issue? @BeetoGuy

**Comment by primetoxinz** [comment]
It was fixed

**Comment by Krhymez** [comment]
So i am assuming in an upcoming update?

**Comment by BeetoGuy** [comment]
Yeah, as soon as a few more things get worked on.
