### ISSUE TITLE
Equipment Storm Breaking

### ISSUE THREAD

**Issue by whimsky** [BetterWithMods/BetterWithMods#604]
Version: 1.12-2.0.14

During storms using a windmill gearboxes only break so far, yet down the line machines (millstone, hopper) break past the broken gearboxes.  

Current setup windmill -> 2 gearboxes broken -> 3 gearboxes -> broken millstone and broken hopper

**Comment by Timeslice42** [comment]
That's not how it works in BTW, but I'm guessing the problem is that it's only a chance to break the gearboxes while they're being overcranked, which would mean that it's possible for overpower to be transmitted down the line breaking machines in an unexpected order.
