### ISSUE TITLE
Server log spam

### ISSUE THREAD

**Issue by darkphan** [BetterWithMods/BetterWithMods#613]
Every time a block is broke with Better With Mods installed, the following gets written to the log file:

[12:45:40] [Server thread/WARN]: Fetching addPacket for removed entity

This can get pretty spammy with several folks on a server and makes it hard to see other messages in the console.

**Comment by YuRaNnNzZZ** [comment]
That occurs not when block is breaked, but when any item is dropped.
Must be related to HCBuoy, because it doesn't occur when its disabled.

**Comment by BeetoGuy** [comment]
Yeah, I'm not entirely sure how to go about catching those.

**Comment by BeetoGuy** [comment]
Lesson learned: Always, ALWAYS copy the ItemStack before doing anything with it.
