### ISSUE TITLE
Mill Stone hunger drain

### ISSUE THREAD

**Issue by Krhymez** [BetterWithMods/BetterWithMods#614]
Currently the Mill Stone drains around 1 hunch every crank. It takes 5 cranks to make flour... and when you cook that bread it barely returns the lost hunger. Is this "working as intended"?

**Comment by BeetoGuy** [comment]
From my experience, that's about right. I swear there was an adjustable config option for exhaustion, however.

**Comment by DaedalusGame** [comment]
you can use a windmill to get bread using *n o* hunger
wheat is midgame and cranking is earlygame so yeah, that's about right

**Comment by Krhymez** [comment]
There is an exhaustion rate.
    hchunger {
        # Set Exhaustion from breaking a block
        D:"Block Breaking Exhaustion"=0.1

        # Passive Exhaustion value
        D:"Passive Exhaustion"=4.0

        # Passive exhaustion tick time
        I:"Passive Exhaustion Tick"=900

        # Gives food poisoning
        B:"Raw Meat is Unhealthy"=true

Those are the defaults. Which is a crazy drain and almost uplayable. I set it to Passive 1.0  tick: 2000  but even that goes down rather fast.  But no matter the settings here, that mill stone drains a lot.

**Comment by DaedalusGame** [comment]
you want Crank Exhaustion under gameplay, that changes how much exhaustion one crank on a handcrank takes. and yes, hunger is supposed to be that harsh because before you get a source of continuous mechanical energy, you're supposed to have a proper food source (chicken with pumpkin seeds for eggs, pigs with kibble, etc)

**Comment by Krhymez** [comment]
I do not see "Crank exhaustion" in the configs. Maybe thats on a newer version?

**Comment by primetoxinz** [comment]
What version are you on?

**Comment by Krhymez** [comment]
1.12.2 with the most recent version of the mod. 

Pack: Primal

I just made a new instance with only "Better with mods" the config is exactly the same. I do not see a "Crank exhaustion". There is a block break and passive though

**Comment by primetoxinz** [comment]
Crank Exhaustion is under the Gameplay feature
https://github.com/BetterWithMods/BetterWithMods/blob/1.12/src/main/java/betterwithmods/module/gameplay/Gameplay.java#L42

**Comment by Krhymez** [comment]
Right, but there does not seem to be a config option for it.  That is a module in the mod itself , but not option to tweak the rates

**Comment by DaedalusGame** [comment]
Crank Exhaustion and Kid Friendly options appear to have disappeared in newer versions. I haven't checked any other configs but it looks like there's a bug with some of these.

**Comment by BeetoGuy** [comment]
Can verify that they're under the "Gameplay" category of the config.

**Comment by Krhymez** [comment]
@BeetoGuy Cool, so "fixed" next update.     I am looking forward to it. Many of the fixes will greatly help my pack.
