### ISSUE TITLE
Apple core tooltips are incorrect

### ISSUE THREAD

**Issue by DeGariless** [BetterWithMods/BetterWithMods#627]
Example: Cooked mutton tooltip shows one hunger bar, but it actually refills 2 hunger bars.

**Comment by primetoxinz** [comment]
This is due to HCHunger changing the hunger bar render, it would have to be a special check for AppleCore as to whether HCHunger is installed.

**Comment by squeek502** [comment]
Can be closed. AppleSkin had specific BWM support (https://github.com/squeek502/AppleSkin/issues/9) but it seems like the scale factor was off.

I've now made AppleSkin use AppleCore's max hunger to get the appropriate scale, so it should now always be correct (as of AppleSkin v1.0.9).

**Comment by primetoxinz** [comment]
Right, forgot about that. Cool
