### ISSUE TITLE
Can't craft wooden gearbox with broken gearbox and two gears. 

### ISSUE THREAD

**Issue by mysteryblock** [BetterWithMods/BetterWithMods#628]
As the title implies. JEI shows this as a crafting recipe, however when hitting the + symbol to place the items from your inventory onto the crafting grid, nothing appears in the output box of the crafting table. 

Minecraft 1.12.2
Better With Mods 2.0.14
Forge .2528

**Comment by BeetoGuy** [comment]
Seems to work on Forge .2503, doesn't seem to be an issue on our end.
