### ISSUE TITLE
Conflict with NotenoughIDs Mod.

### ISSUE THREAD

**Issue by mysteryblock** [BetterWithMods/BetterWithMods#629]
I play with a relatively large collection of mods and have come up against the item limit. Better with mods was working before installing the notenoughids mod to get past this limit, but with this mod installed the soulforged steal anvil's GUI will not pop up.

Not enough IDs: https://minecraft.curseforge.com/projects/notenoughids

Minecraft 1.12.2
Forge .2528
Better With Mods 2.0.14
Notenoughids 1.5.4.2

I'll also reach out to that mod maker and see if it's an issue on their end.

**Comment by DaedalusGame** [comment]
... >_>
