### ISSUE TITLE
HCPiles & HCLumbering and Quarries

### ISSUE THREAD

**Issue by chillar85** [BetterWithMods/BetterWithMods#631]
Hi,
I enabled HCPiles and HCLumbering modules, so i need to use tools to get dirt and woodlogs. But if i use something like a Builder Blocks from RFtools or an Quantum Quarry from Extra Utils 2 i still get piles of dirt and Woodplanks,  Barks and saw dust, even with Silktouch.

I dont know if there is something you guys could to or if the othe mod authors need to do something, but it looks like blocks like quarries arent registered as "tools" as far these two modules are concerned.

Minecraft 1.12.2
Forge 14.23.0.2520
Better with Mods 1.12-2.0.14
Rftools 1.12-7.12
Extra Utils 1.12-1.6.4

**Comment by DaedalusGame** [comment]
For logs, silktouch should definitely work, but it may be fixed in dev only, try the [jenkins build](http://ci.blamejared.com/job/BetterWithMods/)

**Comment by vivagabe** [comment]
I had a similar issue with the Treechop mod.  I figured it wasn’t possible to fix but would be nice to be able to use treechop again.

**Comment by DaedalusGame** [comment]
treechop just needs to harvest the blocks as the player and with the correct tool, instead of just breaking the blocks
