### ISSUE TITLE
Strange results when spawning Items

### ISSUE THREAD

**Issue by mcenderdragon** [BetterWithMods/BetterWithMods#632]
https://github.com/BetterWithMods/BetterWithMods/blob/1.12/src/main/java/betterwithmods/module/hardcore/world/HCBuoy.java#L245

This class is used to replace the EntityItems. But I think this code is outdated as setResult() has no effect on EntityJoinWorldEvent. Also it not canceling the event but killing the spawned item does kill some logic of my mod.

https://github.com/mcenderdragon/Futurepack-API/issues/301

**Comment by primetoxinz** [comment]
Fixed by removing HCBuoy from BWM and making it a separate core-mod rather than event based entity replacement
