### ISSUE TITLE
Please add dirt to slabs and slabs to dirt recipes

### ISSUE THREAD

**Issue by DeGariless** [BetterWithMods/BetterWithMods#639]
![image](https://user-images.githubusercontent.com/7571304/32636682-bb80eba0-c56a-11e7-9a5e-2042d0c9e23b.png)

**Comment by BeetoGuy** [comment]
Looks like the recipes are already there.

**Comment by DeGariless** [comment]
Tested on the latest release. BWM-1.12-2.0.14. with only JEI installed. Recipe doesn't show up in JEI. Tried crafting it anyway. Doesn't work. Maybe it's just not included in the release?

**Comment by DeGariless** [comment]
Looks like its in the latest build from Jenkins
