### ISSUE TITLE
No axel animation when connected to an unpowered gearbox

### ISSUE THREAD

**Issue by DeGariless** [BetterWithMods/BetterWithMods#640]
![image](https://user-images.githubusercontent.com/7571304/32642302-35796b18-c588-11e7-9b01-a4735cc978f8.png)
mechanical power is coming from the top. When I rotate the bottom gearbox to temporarily stop the mechanical power from being transmitted, the top axle continues its animation, while the bottom axle does not. it looks ... weird

**Comment by calloatti** [comment]
I think it works how it should in real life. You are actually disconnecting the gears in the gearbox, the axle before the gearbox should keep working and the ones after the gearbox should stop. Just like a car, the engine keeps running when you are in neutral.

**Comment by DeGariless** [comment]
Correct. I think you misunderstood the issue. There are 2 gearboxes in the screenshot. The one at the top of my screen, and the one at the bottom of my screen. There are also 2 axles in between those gearboxes.
