### ISSUE TITLE
Incompatibility with Energetic Sheep

### ISSUE THREAD

**Issue by rubensworks** [BetterWithMods/BetterWithMods#649]
When this mod is loaded, Energetic Sheep are unable to spawn.
When a spawn is attempted, the following stacktrace occurs: https://pastebin.com/fhMVwSTb

It looks like this is because you're injecting `DataParameter ` entries into instances of sheep. This will cause issues when additional parameters are added to subclasses of `EntitySheep`, which is the case here: https://github.com/CyclopsMC/EnergeticSheep/blob/master-1.12/src/main/java/org/cyclops/energeticsheep/entity/EntityEnergeticSheep.java#L52

So either the `instanceof` check should be made more strict, or another way of injecting data should be added. External additions of `DataParameter` to entities is bound to cause more issues like this, so this shouldn't be done. I used to do it in the past as well for Everlasting Abilities, but changed it to a capability-based system because of the many issues it caused.

P.S.: If possible, it would be nice if this could be resolved before Friday, as this is blocking me from building a BTM booth for Energetic Sheep 😞

**Comment by BeetoGuy** [comment]
Going to implement a stricter check for sheep, at least. Until one of us has the time to convert the whole thing into a capability.

**Comment by primetoxinz** [comment]
Finally put in a properly capability based rewrite for this so this should no longer be an issue.
