### ISSUE TITLE
Platform turns completely invisible when lowering or rising

### ISSUE THREAD

**Issue by DaedalusGame** [BetterWithMods/BetterWithMods#652]
Reported by Darkosto 
https://www.twitch.tv/videos/201042062 around 3:10:00
modpack is SevTech Ages (no public download available)
Supposedly it spams entity errors too, but not sure what exactly.

**Comment by BeetoGuy** [comment]
Yeah, I was watching that and trying to determine what was going on. My best guess is that while the entity does construct properly, which can clearly be seen when the blocks get put back in place, something else is preventing it from spawning.

**Comment by DaedalusGame** [comment]
Fixed in newest forge version
