### ISSUE TITLE
Unable to fill buckets or bottles from flowing water blocks, HCBucket enabled

### ISSUE THREAD

**Issue by dariusfontan** [BetterWithMods/BetterWithMods#655]
I love playing this mod with Hardcore Bucket mode enabled.
Being forced to work for your constant water supply by building canals or aqueducts is so much more interesting and fun.

But I noticed you're unable to fill up a buckets, bottles, cauldrons or anything from a 
"flowing" water block, where in the original Better Than Wolves mod this was totally possible and intended.
Right now you're just able to fill up from water source blocks, like in vanilla Minecraft.
This of course also applies to Screw Pumps, since they don't output a water source block,
but flowing water.

Sadly this kinda breaks the whole hardcore bucket feature for me,
if for filling bottles and such you're still forced to run to the nearest lake or ocean with infinite source blocks.

I tried out the Aqueduct Blocks from Better With Addons, which seem to work well for building canals on the same level as the water source block is. Filling buckets from them works excellent.
But they also don't seem to function with flowing water blocks, they seem to need a source block,
so using Screw Pumps also doesn't work here.

Hopefully you could look into the issue.

Thanks for all your hard work and bringing the awesome Better Than Wolves back to newer MC versions!

EDIT: I'm using the latest version 2.0.14 for MC 1.12

**Comment by BeetoGuy** [comment]
Must have been something that broke since the last time it was addressed. Seems like a lot of things just broke without us touching them after fixing them in this version.

**Comment by dariusfontan** [comment]
Hey, thanks for the response!
I did a bit of testing with different versions of the mod and different Minecraft versions:

The feature seems to be working only with nearly all of the MC 1.11 versions, starting from 1.0.1-1.11.2.
Here you can fill buckets from flowing water just fine, only filling up bottles doesn't work.

In all other versions created for MC 1.12 and also 1.10 the feature just won't work,
I tested quite a lot of the latest and earlier versions for 1.12 and 1.10.

Somehow only the 1.11 versions seem to be working.

Hope this helps!

**Comment by dariusfontan** [comment]
Ok, so I think I figured a way to make it work in MC 1.12, I changed the code a little bit.
I'm by no means a programmer, I just compared the code of the working 1.11 version with the 1.12 version.
In "HCBuckets.java" I simply removed the lines 166-173 and exchanged them with the code from the 1.11 version (lines 168-174 in 1.11 version):

`           } else if (isFluidContainer(evt.getEmptyBucket()) && hardcoreFluidContainer) {
                                ItemStack fill = evt.getEmptyBucket().copy();
                                fill.getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY, null).fill(new FluidStack(FluidRegistry.WATER, 1000), true);
                                evt.setFilledBucket(fill);
                            }
                            evt.setResult(Event.Result.ALLOW);
                            return;`

Seems to be working just fine, filling buckets from flowing water works again, yay!
Bottles don't work of course, as the whole code is just about bucket handling.

Now as I said I have nearly no experience in java programming, so I don't know if changing this tiny bit of code could break something in the 1.12 version. 
That's something you would know.
Anyway, maybe you could test and implement it in the next release.

**Comment by DaedalusGame** [comment]
oh now that you say that, there's been instances where 1.11 fixes have not been merged into the 1.12 branch, so this may be similar, thanks for checking.

**Comment by dariusfontan** [comment]
Glad I could help, keep up the great work!

**Comment by primetoxinz** [comment]
Fixed everything but bottles, will keep this open until then

**Comment by primetoxinz** [comment]
Looked more into glass bottles, would be too hacky.
