### ISSUE TITLE
Broadhead Arrows deal the same damage as Vanilla Arrows when fired from a Composite Bow

### ISSUE THREAD

**Issue by DaedalusGame** [BetterWithMods/BetterWithMods#659]
can somebody confirm this? The wiki says broadhead arrows should have higher damage when fired from a composite bow and approximately travel at twice the velocity.

**Comment by Kevun1** [comment]
I can confirm this. Composite bows currently are inferior to vanilla bows, as they don't do extra damage with broadhead arrows, but they have much slower draw speed.

**Comment by DaedalusGame** [comment]
fuck i knew this may have been someone else, I think COFH core also overrides my greatbow and makes it fire vanilla arrows

**Comment by DaedalusGame** [comment]
this is resolved in COFH Core now.
