### ISSUE TITLE
HCLumber axe recipe not working when config has changed

### ISSUE THREAD

**Issue by Ash70** [BetterWithMods/BetterWithMods#662]
Changing the setting `"Plank Amount"=0` for HCLumber, removes the planks from axe recipe and reverts to the vanilla log to planks recipe.

BWM 2.0.14

**Comment by DaedalusGame** [comment]
I... I'm not sure what the expected result was going to be?

**Comment by Ash70** [comment]
Instead of

Axe + log = planks

It reverts back to

Log = planks

**Comment by therealfarfetchd** [comment]
Unless I'm missing something, it would be impossible to get planks otherwise…

**Comment by Ash70** [comment]
Afaik that config setting is for punching wood. There is also a seperate axe setting.

**Comment by Ash70** [comment]
In other words: why would a craftingtable recipe change when I change a setting for punching wood?

**Comment by DaedalusGame** [comment]
oh i see, now i understand i thought you were bamboozling me, this is probably reasonable for pack development

**Comment by Ash70** [comment]
Sorry for the confusion. I'm terrible at explaining stuff :(
