### ISSUE TITLE
Hellfire should detonate in a stoked cauldron

### ISSUE THREAD

**Issue by LockdownX7** [BetterWithMods/BetterWithMods#674]
Placing any form of hellfire inside a cauldron while it is stoked should cause the hellfire to detonate after a short delay, with the explosion size proportional to the quantity of hellfire present.

**Comment by DaedalusGame** [comment]
this is a BWA feature because it was removed from BWM one time during a code refactor

**Comment by LockdownX7** [comment]
That doesn't seem like the kind of feature that should require an add-on though, especially as blasting oil already detonates when the player carrying it takes damage.

**Comment by primetoxinz** [comment]
Added
