### ISSUE TITLE
Crash with latest BwM (jenkins) (CTM is hard dependency)

### ISSUE THREAD

**Issue by vivagabe** [BetterWithMods/BetterWithMods#681]
[crash-2017-12-02_18.35.32-client.txt](https://github.com/BetterWithMods/BetterWithMods/files/1524448/crash-2017-12-02_18.35.32-client.txt)

I can only get 1.12.2.0.15.204 to launch without problem.  205 and 206 crash...any ideas?

**Comment by mmelvin0** [comment]
Do you have the latest CTM?

**Comment by DaedalusGame** [comment]
That was indeed the problem but it hasn't been fixed yet

**Comment by primetoxinz** [comment]
This should be fixed in 207
