### ISSUE TITLE
HighEfficiencyRecipes should affect wood microblocks

### ISSUE THREAD

**Issue by Tetrajak** [BetterWithMods/BetterWithMods#689]
As the title suggests, I think setting HighEfficiencyRecipes to false should remove all the added recipes for things like item frames, ladders, stairs, etc. that utilise wooden microblocks.

**Comment by primetoxinz** [comment]
I have since removed that submodule as is far too much hassel to config that many recipes.

**Comment by Tetrajak** [comment]
Wouldn't it be as simple as checking the config _before_ adding the recipes to determine whether they should be added at all?

**Comment by primetoxinz** [comment]
No because json recipes are not optional

**Comment by KnightMiner** [comment]
Just add a new recipe condition which checks the config. I do this in most of my mods, especially to check modules.

**Comment by primetoxinz** [comment]
I forgot these existed, so it is in fact possible but it is very low priority anyways. I may do it eventually.
