### ISSUE TITLE
2.0.22 - HCMovement = false but still active

### ISSUE THREAD

**Issue by Tetrajak** [BetterWithMods/BetterWithMods#693]
In version 2.0.22 for MC 1.12.2, setting HCMovement to false does not disable the feature.

**Comment by primetoxinz** [comment]
The full feature can in no way be still enabled while the config false. Commit suicide, your player likely still has the movement attribute.

**Comment by Tetrajak** [comment]
That worked, thank you!

**Comment by primetoxinz** [comment]
Awesome :D
