### ISSUE TITLE
[1.12] Bug with Path making

### ISSUE THREAD

**Issue by MasterEnderman** [BetterWithMods/BetterWithMods#694]
If you change

    hcmovement {
        # Dirt Paths require a shovel greater than stone to be created
        B:"Dirt Paths Require Quality Shovel"=true
    }

to false, you can use every item or block to make paths. This makes it impossible to plant saplings or sugarcane on dirt. It even makes  path blocks, when you place a block on top of grass or dirt.

**Comment by primetoxinz** [comment]
lol
