### ISSUE TITLE
Infernal Enchanter Can Be Broken Instantly With No Tool

### ISSUE THREAD

**Issue by TechnoMysterio** [BetterWithMods/BetterWithMods#695]
The infernal enchanter can be instantly destroyed, with or without a tool. However, it only drops itself as an item if you break it with a pickaxe.

This should probably be changed so that it is more in line with the standard enchantment table: taking about a second to be destroyed with a pickaxe, and longer with a bare hand/the wrong tool.

**Comment by primetoxinz** [comment]
Just an oversight, will fix it

**Comment by primetoxinz** [comment]
Was fixed in last commit
