### ISSUE TITLE
HCLumber + HCPiles drops wrong item for last hit

### ISSUE THREAD

**Issue by mmelvin0** [BetterWithMods/BetterWithMods#704]
If you use a stone axe on a log, the last hit where the tool breaks drops planks and sawdust instead of the log. Same deal with HCPiles and shovels.

It happens because the block harvest event fires after the main hand already contains an empty item stack when the tool is destroyed.

I made a slightly convoluted pull request with a fix: #703.

**Comment by primetoxinz** [comment]
Too fast for you ;)
