### ISSUE TITLE
[Suggestion] A config blacklist for HCHunger food values changes

### ISSUE THREAD

**Issue by Pyrofab** [BetterWithMods/BetterWithMods#711]
Some mods like The Betweenlands already have [some sort of food mechanic to complicate gameplay](http://the-betweenlands.wikia.com/wiki/Food_Sickness). It could be nice to be able to prevent their food from being further rebalanced.

**Comment by primetoxinz** [comment]
HCHunger is a whitelist, I only modify specific foods. This should not change food from other mods.

**Comment by primetoxinz** [comment]
I take that back, I forgot it is because I scale the hunger bar by 3 for more specific values. I'll simply scale any food that isn't mine.
