### ISSUE TITLE
Better with mods recipes not overrideable with craftweaker

### ISSUE THREAD

**Issue by mvdhoning** [BetterWithMods/BetterWithMods#713]
For my modpack i want to replace the iron in the rustic mod candle with wrought iron.
What works fine except not for the candle recipe added by better with mods.

This is the crafttweaker script:

```
recipes.remove(<rustic:candle>);
recipes.addShaped(<rustic:candle>*6, [[<ore:string>],[<ore:tallow>], [<ore:ingotWroughtIron>]]);
recipes.addShaped(<rustic:candle>*4, [[<ore:string>],[<ore:wax>], [<ore:ingotWroughtIron>]]);
```

How can i remove the candle recipe from better with mods that now still uses iron instead of wrought iron.
I do want to keep the rest of recipes added by better with mods for rustic.

btw: wrought iron is from garden stuf and is made with iron and sand and (char)coal in a bloomery.

**Comment by primetoxinz** [comment]
This is my fault, the Rustic compatibility recipes are registered too late for craft tweaker, I'll fix it when I get the chance
