### ISSUE TITLE
[Suggestion] Consider Quark's boat sails for HCBoating speed boost

### ISSUE THREAD

**Issue by Pyrofab** [BetterWithMods/BetterWithMods#716]
Quark already adds boat sails as a vanity feature. Given that banners have roughly the same cost as windmill sails, it could be interesting and more immersive to consider those sails as such.

**Comment by primetoxinz** [comment]
Considering the core mod nature of the quark sails it might be rather difficult to detect

**Comment by Pyrofab** [comment]
It looks like it wouldn't be too difficult if you query the data manager. However, the (data parameter)[https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/vanity/feature/BoatSails.java#L32] is private so you may have to either ask vazkii to change it or use reflection. I don't really know if it's worth the effort but it could be quite neat of a feature to have.

**Comment by primetoxinz** [comment]
as the data is just saved to the boat's nbt I can just test if the key exists, I already have it mostly implemented testing now.

**Comment by primetoxinz** [comment]
To make this actually work you will need to regenerate the HCBoats Speed Items config or simply add `  "minecraft:banner:*=100"` to it yourself
