### ISSUE TITLE
Missing textures while hand crank is active [1.12-2.0.23]

### ISSUE THREAD

**Issue by scootz** [BetterWithMods/BetterWithMods#717]
Noticed missing textures in Waila? while operating the hand crank for states 1-7.

![applicationframehost_2018-01-01_14-45-25](https://user-images.githubusercontent.com/574344/34470668-a4390f2c-ef04-11e7-883d-e2b18f6efa46.png)

**Comment by primetoxinz** [comment]
not really fixable on my end
