### ISSUE TITLE
[1.12.2] Hemp seeds can't be used in farms from Ancient Warfare 2 and Minecolonies

### ISSUE THREAD

**Issue by Kiyaku** [BetterWithMods/BetterWithMods#724]
Heya,

was testing out ancient warfare 2 and minecolonies and wanted the NPCs to auto farm hemp. Unfortunately the seed can't be used in any of their farms (for ancient warfare 2 it can't be put into the farms "Resource" slot, and for Minecolonies putting it into the scarecrow and giving seeds to the farmer doesn't do anything, they don't start planting them). 

Other seeds seemed fine so i'm not sure if this issue is part of BWM or with AW2/Minecolonies. 

If you need any more info about how i tested/set it up or something, let me know! 

Cheers,
SC

**Comment by primetoxinz** [comment]
I believe this was all working
