### ISSUE TITLE
MechanicalUtil should probably somehow be proxied as part of the API

### ISSUE THREAD

**Issue by asiekierka** [BetterWithMods/BetterWithMods#725]
For usage by other mods implementing IMechanicalPower, if any.

**Comment by primetoxinz** [comment]
done :)

**Comment by primetoxinz** [comment]
whoops just realized I shouldn't do it that way

**Comment by primetoxinz** [comment]
https://github.com/BetterWithMods/BetterWithMods/blob/7aecd2f8c394a1119449521ebedc98901273fda5/src/main/java/betterwithmods/api/BWMAPI.java
