### ISSUE TITLE
Gloom Overrides don't work in off hand

### ISSUE THREAD

**Issue by zcorcoran** [BetterWithMods/BetterWithMods#728]
Light sources registered in the config as Gloom overrides work as expected in the main hand, but have no effect in the off hand. Since this is meant to work alongside Dynamic Lights, it seems like the off hand should also work, since both AtomicStyker's mod and Optifine produce light when a light source is held in either hand.

Just to be sure it wasn't a weird conflict, I tested this with only BWM 1.12-2.0.24 and Forge 14.23.1.2586 installed and minecraft:torch:0 registered as the sole gloom override item, and welp: https://imgur.com/a/BcUph

**Comment by primetoxinz** [comment]
Should be fixed in next release
