### ISSUE TITLE
[1.12.2] Gear boxes break instantly 

### ISSUE THREAD

**Issue by GWSheridan** [BetterWithMods/BetterWithMods#732]
Gear boxes break instantly in the nether using the vertical windmill
Sometimes can get the gear boxes to work with the normal windmill
I tried to clear weather in the nether to see if this was the issue an didn't seems to fix it

Versions
BWM: 1.12.2-2.0.24
Forge: 14.23.1.2587
MC: 1.12.2

**Comment by GWSheridan** [comment]
Is there a way to disable the breaking gear boxes

**Comment by primetoxinz** [comment]
Oh, this issue is fixed in dev. But do you still want a config for breaking?

**Comment by GWSheridan** [comment]
Ye as forever stranded uses BWM early game. I dont mind if theres no config just thought there may of been away I might of missed
