### ISSUE TITLE
[1.12.2] Player clipping through the moving elevator (built from platforms)

### ISSUE THREAD

**Issue by iarspider** [BetterWithMods/BetterWithMods#733]
If the player isn't looking straight forward while riding an elevator (3x3, 4 tall hollow box), there is high chance he will clip through the top of the box.

Forge 2560,
BetterWithMods 2.0.24

**Comment by iarspider** [comment]
Even with the flat platform if the player is not looking straight the movement of the player on that platform will not be smooth.

**Comment by therealfarfetchd** [comment]
I can't reproduce this, but I have an idea on how to fix this stuff once and for all.

**Comment by primetoxinz** [comment]
Is this on a server or just single player?

**Comment by therealfarfetchd** [comment]
The platform movement is definitely not influenced by the direction the player looks in. Do you have any other mods installed or only BWM?

**Comment by primetoxinz** [comment]
Going to close this unless someone can reproduce or give more information
