### ISSUE TITLE
Wooden button and pressure plate recipes gone when using rustic compat module

### ISSUE THREAD

**Issue by Aphyxia** [BetterWithMods/BetterWithMods#737]
Wooden pressure plate and button recipes are gone when using Better with mods and Rustic together with rustic compatibility module enabled. 
The boolean on 
`rustic {
        # Enables custom recipes provided by this feature
        B:"Custom Recipes"=false
    }`
does not affect this, only the `B:rustic_compat=true`. Setting it to false enables the recipes again.
Is this by design or is it a bug? If by design then how are these items made obtainable?

Mods and MC used:
Rustic 0.4.7
BwM 1.12-2.0.24
MC 1.12.2
Forge 14.23.1.2587

**Comment by primetoxinz** [comment]
Fix in next release
