### ISSUE TITLE
Cannot turn off Hardcore Strata 

### ISSUE THREAD

**Issue by Adarcer** [BetterWithMods/BetterWithMods#738]
BetterWithMods-1.12-2.0.14

Not sure if its your mod as I updated quite a few mods but it seems strata is on even with hardcore hardness turned off I get normal stone to approx level 52 , then darker stone to 53-33 at 33 stone starts too look like bedrock and stone takes forever too mine. the pack has vanilla tools disabled, and even with diamond upgrade on tconstuct tool the bedrock like stone does not break any faster than with a copper, iron even manyullyn pick.

tried removing the .cfg file to regen new .cfg thinking that maybe the old config was the problem but a new config did not generate.

edit: I downgraded to 2.0.14 to try too fix issue but had upgraded too BetterWithMods-1.12-2.0.24.jar

**Comment by primetoxinz** [comment]
This *should* already be fixed in dev http://ci.blamejared.com/job/BetterWithMods/284/

**Comment by primetoxinz** [comment]
Can you confirm this?

**Comment by Adarcer** [comment]
Problem was .cfg was not generating so the hardcore strata was unable too be turned off... took a little while but finally got it too generate.

**Comment by primetoxinz** [comment]
bizarre

**Comment by Adarcer** [comment]
I upgraded from a version that did not have hardcore strata to one that did ... should have realized that i would need a new config, but thought it would just update config and add new values.

**Comment by primetoxinz** [comment]
Yeah, it does add new values something funky happened
