### ISSUE TITLE
BWM Windmill not turning axles since latest update.

### ISSUE THREAD

**Issue by medina102** [BetterWithMods/BetterWithMods#741]
I am a tester for Lost souls GWSheridans pack and for some reason since yesterdays update the BWM windmill does not turn the axles but the immersive engineering one does.  (The vertical windmill is perfectly fine)    (Everything is in the Nether)

**Comment by primetoxinz** [comment]
Ah, yes. The horizontal windmill was never intended to work in the nether, it was a bug that got fixed in the latest release

**Comment by primetoxinz** [comment]
I'll add this to the Book of Single so it doesn't seem like a bug in the future

**Comment by medina102** [comment]
Ahh ok excellent 👍
