### ISSUE TITLE
wooden gearboxes breaking in the nether

### ISSUE THREAD

**Issue by ZeroLyfe** [BetterWithMods/BetterWithMods#745]
I'm playing GWSheridans Forever Stranded Lost Souls pack version 1.0.4 with Better With Mods version 1.12-2.0.25 .
 Wooden gearboxes break when driven by the Immersive Engineering windmill in the nether.  It doesn't matter if the gearbox or the windmill is placed first as soon as the gearbox gets power from the axle it breaks. I've tested by putting a random things rain shield next to the windmill and also gone into creative and changed it to a new day and turned rain off and the gearbox still breaks instantly with no delay.

**Comment by primetoxinz** [comment]
I'll look into why but the IE windmill is making more power in the nether and thus causes the gearbox to be overpowered.
