### ISSUE TITLE
HCBucket in other dimensions

### ISSUE THREAD

**Issue by Efimero** [BetterWithMods/BetterWithMods#749]
for some reason the HCBucket module looks for the overworld dimension to work
in other dimensions you can place water like in vanilla no matter the setting and right-clicking with the vanilla bucket hurts no matter which block you click on (???)
it is really confusing getting hurt when taking water from the twilight forest, for example

**Comment by DaedalusGame** [comment]
What the fuck, this sounds like a compound bug caused by an intended behavior. Basicly water buckets have to work in the End, that's why it checks for the overworld, probably. (It should probably be a dimension config) The fact you get hurt is very silly.

**Comment by Efimero** [comment]
yeah, I am seeing this happen now in the overworld too, so I think it's not your fault after all, but if you could double check, it would help
it must be an interaction with some other mod, as earlier I also observed wrong behaviour when adding water to Ceramics' clay barrels, but I don't know what else touches these events (PrimalCore???)

**Comment by primetoxinz** [comment]
Can you test killing yourself with the damage that the water bucket causes and tell me what the death message is? I can't really confirm if this is due to our lava bucket code or not

**Comment by Efimero** [comment]
I did and it is lava damage, forgot to say that, I have a video of it too

**Comment by primetoxinz** [comment]
Do you have this config enables?
```
  hcbuckets {
       # You can't put Lava in a metal bucket! Are you crazy!?
        B:"Hardcore Lava Buckets"=true
}
```

**Comment by Efimero** [comment]
yeah, that's what I meant, when that is on, I get the damage, when it's off, works as vanilla

**Comment by Efimero** [comment]
I think I figured out one of the thing that was happening
on the version before the last commit you had `e.getTarget().getBlockPos() != null`, but it may not be ever returning null, instead going to coords 0 0 0
in my world, 0 0 0 was usually unloaded, so that worked fine, but when I started using /tpj to go to dimension, that puts you on the 0 0 column of the dimension, so it would load that block
and again, in my world, I use bedrockReplacer to turn the bottom layers into... LAVA!!!
sso it was not an issue until the 0 0 chunk was generated, and then it was finding the lava block at 0 0 0 that exists only in my specific worlds
!!!FUN!!!

**Comment by Efimero** [comment]
feature is fixed, but could be improved by adding other hot liquids to the list of dangerous stuff, like blazing pyrotheum =P
