### ISSUE TITLE
[SUGGESTION] Natura

### ISSUE THREAD

**Issue by Okii35** [BetterWithMods/BetterWithMods#750]
Hello.
Just an idea to make compatible the natura planks with the saw.

**Comment by primetoxinz** [comment]
This is an issue on Natura's side, all the saw needs is the logs and planks to be in `logWood` and `plankWood` oredictionary entries respectively.

**Comment by Okii35** [comment]
Ah ok. Thanks

**Comment by Okii35** [comment]
To make 1/4 Planks, 1/8 Planks, gear ,etc We just have to add our plank in the plankwood oredictionnary  ?

**Comment by primetoxinz** [comment]
Ah, no I didn't know you were referring to adding miniblocks I thought you couldn't get planks from the log.
Currently I don't want to add new miniblock types as I am working on making it much easier to add.
