### ISSUE TITLE
Texture issue (in combination with BOP)

### ISSUE THREAD

**Issue by Cypress187** [BetterWithMods/BetterWithMods#752]
When I set compatmodule BiomesOPlenty on true, the textures of another mod are broken (Lootbags). Some code in the compat_module breaks textures. You can test it by making a modpack of below mods and slay a zombie, or go in to gamemode ;)

Installed mods:

forge-1.12.2-14.23.2.2613-universal
BetterWithMods-1.12-2.0.25
BiomesOPlenty-1.12.2-7.0.1.2302-universal
LootBags-1.12.2-2.5.3b

It's fixed when BOP compat is set to false.

**Comment by DaedalusGame** [comment]
apparently this might be resolved now, you can get a new build from [the jenkins](http://ci.blamejared.com/job/BetterWithMods/). If it's not resolved comment and I will reopen.
