### ISSUE TITLE
Improved Flee causes wolf aggro

### ISSUE THREAD

**Issue by LockdownX7** [BetterWithMods/BetterWithMods#753]
In multiplayer, the feature where animals flee when a block is placed/harvested, causes tamed wolves to attack the player that placed the block, as if they had punched the wolf.

**Comment by mmelvin0** [comment]
It also causes llamas and Animania bulls to aggro.

I'm not sure if I even want this fixed for llamas and bulls, but for wolves it's a bit problematic.
