### ISSUE TITLE
[Modtweaker Compatibility] Rustic Saw Modtweaker

### ISSUE THREAD

**Issue by Okii35** [BetterWithMods/BetterWithMods#754]
Hello

I write that in my zen script. I know that's correct but no works.
(that works with rustic's slate block)

mods.betterwithmods.Saw.add([<betterwithmods:rustic_compat_moulding>*2], <betterwithmods:rustic_compat_siding>);
mods.betterwithmods.Saw.add([<betterwithmods:rustic_compat_corner>*2], <betterwithmods:rustic_compat_moulding>);

mods.betterwithmods.Saw.add([<betterwithmods:rustic_compat_moulding:1>*2], <betterwithmods:rustic_compat_siding:1>);
mods.betterwithmods.Saw.add([<betterwithmods:rustic_compat_corner:1>*2], <betterwithmods:rustic_compat_moulding:1>);

Any idea ?

**Comment by primetoxinz** [comment]
it's not correct as you need to surround the item names witth `<>`, it should be `<betterwithmods:rustic_compat_corner>*2`

**Comment by Okii35** [comment]
OMG. Sorry. I don't see that. The copy paste of "CT Hand" is effective but suddenly going too fast I have not seen the forgetting of <>. I gonna try that tonight. And one last question, the HCboat changes the speed of the boat?

**Comment by primetoxinz** [comment]
No problem. 
Yes, HCBoats make a boat without a sail slow. By holding a sail (the same item used for crafting windmills) in your hand you will go faster.

**Comment by Okii35** [comment]
ok thanks to explain the boat.
by the way my script was correct for example:

mods.betterwithmods.Saw.add([<betterwithmods:rustic_compat_moulding>*2], <betterwithmods:rustic_compat_siding>);

I do not know why the <> were not paste the first time.
i need to import something like that "import crafttweaker.item.IIngredient;" or not.

**Comment by Okii35** [comment]
ok i know. 
It thinks I want to insert a code with the syntax <>. But believe me i write the <> in my script.

**Comment by Okii35** [comment]
My script
[https://text-share.com/view/ec135aa4](url)
