### ISSUE TITLE
fishing loottable broken in 1.12-2.0.25

### ISSUE THREAD

**Issue by dskw** [BetterWithMods/BetterWithMods#756]
Version: BetterWithMods-1.12-2.0.25
Error: Couldn't load loot table betterwithmods:gameplay/fishing
Log: https://pastebin.com/ZrKr7t9x

Description:
Looks like the fishing loottable is invalid.
I also had the problem that HCFishing = true with Bait=false resulted in never getting anything through fishing. I assume this is caused by the loottable. I had to disable HCFishing for now to use the vanilla loottables.

**Comment by primetoxinz** [comment]
Fixed in next release
