### ISSUE TITLE
Planter Shovel TiC

### ISSUE THREAD

**Issue by Kenshij** [BetterWithMods/BetterWithMods#759]
Hello,

the removing from Planter does not work with TiC tool shovel, can you fix this please.

**Comment by DaedalusGame** [comment]
```
if (meta != 6 && !heldItem.isEmpty() && heldItem.getItem().getHarvestLevel(heldItem, "shovel", player, planter) > -1)
```
our code does this and if this doesn't work  this is entirely their fault.
(there's no check for instanceof ItemShovel)
