### ISSUE TITLE
IMechanicalPower logic question

### ISSUE THREAD

**Issue by asiekierka** [BetterWithMods/BetterWithMods#764]
```
if (overpowerChance() && findPower > getMaximumInput(EnumFacing.UP)) {
```

Shouldn't this, instead, have a "boolean overpowered" flag and replace "findPower = power;" with:

```
findPower = power;
overpowered = findPower > getMaximumInput(facing)
```

? That would allow different maximum inputs for each face without... issues.

(The equals sign for overpowered could also be an |=, depending on your balance decisions)

**Comment by DaedalusGame** [comment]
this is fantastic just yesterday primetoxinz was milling me about a coding sin of mine now he's hoise by his own petard

**Comment by asiekierka** [comment]
Nice. Thanks!

**Comment by DaedalusGame** [comment]
if it works
