### ISSUE TITLE
[Console Errors]: As Discussed on Discord

### ISSUE THREAD

**Issue by Lanse505** [BetterWithMods/BetterWithMods#767]
@primetoxinz 

Recipe Errors due to Missing output:
https://gist.github.com/Lanse505/c5be6631ee80853f2ebe00558552bf36

Malformed Json Errors:
https://gist.github.com/Lanse505/bea5d446d758adef04f3e92e329a9744

^ Mind you this error prints multiple times, once for each mod trying to access the loot pools.

**Comment by primetoxinz** [comment]
Fixed in next released.
