### ISSUE TITLE
Kiln smelts ores to ingots even when "Ore To Nugget Smelting"= true

### ISSUE THREAD

**Issue by DeGariless** [BetterWithMods/BetterWithMods#770]
HCOres=true
    "Dust to Nugget Smelting"=true
KilnSmelting=true
    "Ore Production Count"=3

Kiln smelts 1 ore to 3 ingots. I expected 3 nuggets

**Comment by primetoxinz** [comment]
`HCOres - Ore to Nugget Smelting` must also be true

**Comment by DeGariless** [comment]
Almost certain oretonugget is set to true. I guess I will double check when I get home.

**Comment by DeGariless** [comment]
Fresh install with default configs and only the following mods

Forge - build 2611
Better With Mods - build 300
JEI - build 147

(default config but I checked anyway)
HCOres = true
KilnSmelting = true
"Ore to Nugget Smelting" = true

Kiln still smelts to ingots. Am I missing something?

**Comment by BeetoGuy** [comment]
There are cases where if an ingot doesn't have an associated nugget, it defaults to ingots. At least, that's how it should be working.

**Comment by DeGariless** [comment]
I'm just trying to get gold and iron to work correctly at this point
