### ISSUE TITLE
[Cross-Mod Bug]: BWM + BoP breaks Advanced Rocketry's Rendering

### ISSUE THREAD

**Issue by Lanse505** [BetterWithMods/BetterWithMods#772]
Tested using:
Minecraft: 1.12.2
Forge: 14.23.2.2619
Advanced Rocketry: 1.12.2-1.2.6-57
BetterWithMods: 1.12-2.0.25
BiomesOPlenty: 1.12.2-7.0.1.2302-universal
Hwyla: 1.8.23-B38_1.12
JEI: 1.12.2-4.8.5.157
LibVulpes: 1.12.2-0.2.8-27

This can be reproduced with HCStrata turned off as well, tested per @DaedalusGame 's request in discord.

As long as both BoP and BWM are present in the same modded environment it breaks Advanced Rocketry's Rendering for most blocks.

Working Vs Non-Working:
https://i.imgur.com/sveUfTn.png
https://i.imgur.com/grqWsSE.png

This is also reproducible with only:
Advanced Rocketry,
BetterWithMods,
BiomesOPlenty 
& LibVulpes.

**Comment by Lanse505** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1174
https://github.com/Glitchfiend/BiomesOPlenty/issues/1190

**Comment by DaedalusGame** [comment]
i think this is resolved now probably
