### ISSUE TITLE
(1.12.2) Hardcore Beacon Using Glowstone Night-Vision Flicker

### ISSUE THREAD

**Issue by TechnoMysterio** [BetterWithMods/BetterWithMods#773]
When a beacon is made out of glowstone and activated to get the night-vision effect, a problem occurs with the fact that the night-vision is constantly pulsing.

This is due to the fact that the night-vision is always about to end, counting down from 6 to 0 before resetting, meaning that the vanilla effect of night-vision flickering when the effect is about to wear off (at 10 seconds remaining) is constantly present. Perhaps set it to 20 seconds and reset it at 14 or something similar.

BWM: 1.12-2.0.25
Forge: 14.23.2.2619
MC: 1.12.2

**Comment by DaedalusGame** [comment]
it's already set to 20 seconds it seems so idk whats wrong with that

**Comment by primetoxinz** [comment]
I don't think I ever released with it

**Comment by DaedalusGame** [comment]
that explains it

**Comment by primetoxinz** [comment]
Fixed for next release
