### ISSUE TITLE
[suggestion] functional wells

### ISSUE THREAD

**Issue by stohun01** [BetterWithMods/BetterWithMods#774]
Using an empty bucket anywhere on a line of rope that's hanging directly above a source block consumes the source block and fills the bucket. This would allow you to build realistic looking wells when you find those pockets of water underground.

**Comment by primetoxinz** [comment]
![img-2018-03-03-224110](https://user-images.githubusercontent.com/4721642/36942383-441b08ba-1f3e-11e8-8cfa-79b64615bbe6.png)
