### ISSUE TITLE
[1.12.2] [REQUEST] Add possibility to obtain flint with HCPiles active...

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#777]
When I mine gravel with my hand, I get only piles of gravel, but I can not get flint. For my Modpack, it is necessary to be able to get flint to start being able to cut trees and get wood. I love the functionality of HCPiles to get 3 batteries instead of a block when mine with my hands, but it would be necessary to be able to get flint also in set way.

I do not like Flint using 2 or 3 Gravel block in its crafting table, so I wish I could remove it, but now it's the only way to start a game.

Can you please look to add a config for or possibility to get flint using our hand...

Thank's
Fireztonez

**Comment by primetoxinz** [comment]
Think this was resolved
