### ISSUE TITLE
CADs (from Psi) create Grass Paths when Better With Mods is installed

### ISSUE THREAD

**Issue by rileduphunt** [BetterWithMods/BetterWithMods#778]
In Minecraft 1.12.2, when Better With Mods is installed alongside Psi, right-clicking a Grass Block with a Casting Assistance Device turns the Grass block into a Grass Path. Stone and Wooden Shovels do not create Grass Paths when used on a Grass Block anymore.

Tested in Minecraft 1.12.2 with Psi r1.1-59, AutoRegLib 1.3-15, Better With Mods 1.12-2.0.25, Forge 14.23.2.2611. MultiMC used as launcher.

FML Log: https://paste.ee/p/sf0h6

**Comment by DaedalusGame** [comment]
i have no idea why CADs make grass paths but wooden and stone shovels don't make them if the config `Dirt Paths Require Quality Shovel` is enabled

**Comment by primetoxinz** [comment]
Because CADs are in every vanilla toolclass and always have the highest vanilla harvest level

**Comment by DaedalusGame** [comment]
this sounds intentional then

**Comment by primetoxinz** [comment]
Yeah, was looking into whether we could skip the BlockRightClickEvent if there was a valid onItemUse but it happens afterwards, The only real way to fix this is a blacklist, unfortunately.
