### ISSUE TITLE
[Suggestion] Config option to disable fat

### ISSUE THREAD

**Issue by Pyrofab** [BetterWithMods/BetterWithMods#787]
Hardcore hunger is very interesting to work with but the fat mechanism tends to make saturating food worthless. It would be nice to have a configuration option to keep all the other penalties of hardcore hunger (health regen nerf, passive hunger loss...) without the fat.

**Comment by DaedalusGame** [comment]
From a cursory look fat used to be disableable and i'm pretty sure saturation still affects how much fat is gained if the item is either a dessert or eaten when you have full hunger.

**Comment by primetoxinz** [comment]
Fat is such an integral part of HCHunger that you might as well not use the whole feature. No thanks
