### ISSUE TITLE
Risky lava buckets sync issue

### ISSUE THREAD

**Issue by mmelvin0** [BetterWithMods/BetterWithMods#789]
I noticed when playing with risky lava buckets it the following happens: Lava block is dropped and player appears to catch on fire, but doesn't take any damage. Also the lava block doesn't flow. If I right click again with the (seemingly empty) bucket it actually places the lava block. The first one disappears and the new one flows. I'm thinking it may be a client/server side issue.

I'm just making a note of this, may be able to provide better info or a pull request later.

**Comment by mmelvin0** [comment]
Works perfectly now in 2.0.30, thank you!

**Comment by primetoxinz** [comment]
\o/
