### ISSUE TITLE
[1.12.2] Broken Stone Button And Pressure Plate recipe

### ISSUE THREAD

**Issue by EmosewaPixel** [BetterWithMods/BetterWithMods#790]
In the latest version of the mod, the wooden Pressure Plate and Button have the recipes for the stone variants:
![image](https://user-images.githubusercontent.com/25333164/37306336-aff1dd70-2637-11e8-8711-5ecee0e18154.png)

**Comment by DaedalusGame** [comment]
copypaste at work
