### ISSUE TITLE
[1.12.2][Issue][Compatibility] Noneffective hoe drop Hemp Seed

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#791]
With Pickle-Tweaks, I added to "useless_hoes" option, so the wooden hoe can't tilt the dirt anymore... When I right-click a block, nothing happen, but some times a Hemp Seed droped. The problem is the fact of that tool is unbreakable because of the fact of is does nothing, and is can drop an infinite quantity of seed from one block of dirt... I can easely imagine automate an 

The problem is with the way you verify if use hoe for drop seed, You should probably verify the fact the block transform to farmland, before drop the seed. I know by example Actually Addition work that way, because the block didn't drop any worm when I use that hoe.

Possibly you can change way you make the verification or add a tools blacklist option for the drop.

BWM: 1.12-2.0.28
Minecraft: 1.12.2
Forge: 14.23.2.2625
PickleTweaks: 2.0.9

Thank's again for you awesome mod and for your good work!!
Fireztonez

**Comment by primetoxinz** [comment]
Fixed in next release

**Comment by Fireztonez** [comment]
Thank you for the fix and for your amazing mod!!
 Continue your great work!
