### ISSUE TITLE
[1.12.2] Cannot Remove The Nugget Smelting Recipes Via CraftTweaker

### ISSUE THREAD

**Issue by EmosewaPixel** [BetterWithMods/BetterWithMods#792]
So I wanted to have an alternative way of making Draconium. I tried to remove the Ore to Nugget and Dust to Nugget smelting recipe with just the output and with the input and output, but it's still there.

**Comment by DaedalusGame** [comment]
Can you test if this is still a problem using the [newest jenkins build](http://ci.blamejared.com/job/BetterWithMods/)?

**Comment by EmosewaPixel** [comment]
Yup, that fixed it!
