### ISSUE TITLE
For what purpose melons

### ISSUE THREAD

**Issue by DaedalusGame** [BetterWithMods/BetterWithMods#793]
https://github.com/BetterWithMods/BetterWithMods/blob/d5a1c9e004e25a0a1cf6b28047c8b29c62cae604/src/main/resources/assets/betterwithmods/recipes/decompress/melon_decompress.json#L9

**Comment by primetoxinz** [comment]
probably copy pasted another decompress recipe :P

**Comment by DaedalusGame** [comment]
the copypaste needs to stop please i'm losing my sanity

**Comment by primetoxinz** [comment]
no
