### ISSUE TITLE
Incorrect HCDiamond recipe for diamond hoe/axe

### ISSUE THREAD

**Issue by justinrusso** [BetterWithMods/BetterWithMods#795]
The recipe for the diamond axe (which is missing) is currently associated with the diamond hoe.

![image](https://user-images.githubusercontent.com/25138621/37440309-921d5792-27d2-11e8-81a2-517cbd479f6f.png)

**Comment by justinrusso** [comment]
Also, Id assume that these recipes are supposed to replace the vanilla recipes? If so, none of the tools' default recipes are being removed.

**Comment by primetoxinz** [comment]
What version of BWM are you running?

**Comment by justinrusso** [comment]
Oops... 1.12-2.0.28-363. I cant recall forge version but its the same as Beta 3 SevTech

**Comment by primetoxinz** [comment]
I just found part of the issue. I'll look more into the recipes not being removed soon

**Comment by primetoxinz** [comment]
It appears that the normal diamond hoe recipe still existing is a pack bug as it doesn't happen on my end.
