### ISSUE TITLE
[1.12.2] The Observer Has The Dropper And Dispenser Recipe

### ISSUE THREAD

**Issue by EmosewaPixel** [BetterWithMods/BetterWithMods#797]
![image](https://user-images.githubusercontent.com/25333164/37518493-a3a5bace-2915-11e8-96ff-fa966d0fb345.png)

**Comment by DaedalusGame** [comment]
duplicate of #785 ? how is this still broken if it was fixed in f1bad2d?

**Comment by EmosewaPixel** [comment]
I though you only fixed it for the button and pressure plate last time....
