### ISSUE TITLE
Crash w/o the CTM mod

### ISSUE THREAD

**Issue by Bulldog83** [BetterWithMods/BetterWithMods#801]
Minecraft: 1.12.2
BetterWithMods: 1.12-2.0.29
Forge Server: 14.23.2.2611
SpongeForge: 2611-7.1.0-BETA-2963

BWM config: https://gist.github.com/Bulldog83/085aef1c425db838d62217cefacac4d2
Crash-report: https://gist.github.com/Bulldog83/ca51eef269a1ec4fde13c330208ee1c3

**Comment by DaedalusGame** [comment]
Duplicate of #800 
You can find the fix [here](https://ci.blamejared.com/job/BetterWithMods/)

**Comment by Bulldog83** [comment]
Ok, thanks.
