### ISSUE TITLE
[Recipe] Mill Stone

### ISSUE THREAD

**Issue by artdude543** [BetterWithMods/BetterWithMods#816]
Heyo!

SevTech: Ages updated and added some dye recipe fixes/additions. But it seems the Mill Stone is acting oddly in regards to we have the following recipes being added

```
Mill.add(<ceramics:unfired_clay:4>, null, [<minecraft:dye:15>, <minecraft:clay_ball>, <minecraft:flint>]);
Mill.add(<pickletweaks:dye_powder:15> * 2, null, [<minecraft:dye>]);
```

The recipes show in JEI no problem, but when you use the Mill Stone with the top recipe added to the GUI only the Bone Meal -> Dye is performed it's like it's ignoring all the other items for the Unfired Recipe?

Is this an issue with CT or the Mod? Thanks! :)

**Comment by DaedalusGame** [comment]
i think this is a recipe priority issue aswell, i can look into fixing this on this version; we already have a full crafting system refactor that should fix any priority issues. 
The top and bottom recipes appear to use different dyes though, the bottom one apparently uses ink sacs?

**Comment by artdude543** [comment]
Yeah sorry pasted the wrong script line. But yeah seems like a priority issue if this could be patched that would be awesome 😊

**Comment by DaedalusGame** [comment]
Probably resolved

**Comment by artdude543** [comment]
Do you have CI builds @DaedalusGame?

**Comment by primetoxinz** [comment]
Our CI is currently down unfortuantely.

**Comment by justinrusso** [comment]
I thought you used jareds?

**Comment by primetoxinz** [comment]
We do. It is down.

**Comment by justinrusso** [comment]
https://ci.blamejared.com/ O_o

**Comment by primetoxinz** [comment]
As you can see, ours is currently not available as the server died recently.

**Comment by artdude543** [comment]
Could a build with this fix be pushed to CurseForge?

**Comment by primetoxinz** [comment]
It will be soon
