### ISSUE TITLE
[TileEntity] Water Wheel

### ISSUE THREAD

**Issue by artdude543** [BetterWithMods/BetterWithMods#820]
Hello!

Uses are SevTech are now facing a new bug with the WaterWheel which is causing crashes and players to not be able to re-join servers/worlds. The log is here: https://paste.ee/p/e57ZT

If you guys could look into it that would be awesome!

Thanks

**Comment by primetoxinz** [comment]
Fixed in 2.0.32. Putting on curse now with a couple other fixes.

**Comment by artdude543** [comment]
Awesome thanks again! 😄
