### ISSUE TITLE
Manual - Document not found

### ISSUE THREAD

**Issue by owetre18** [BetterWithMods/BetterWithMods#823]
Here is my config file, if it matters: https://pastebin.com/YmNPVmcu

Here is what I get when I use the book. It says to report the issue here, so I am:
![2018-03-29_22 21 13](https://user-images.githubusercontent.com/5685621/38121817-8d1319fc-339f-11e8-90e6-eaccb5aca067.png) 

I'm using "BetterWithMods-1.12-2.0.32"

**Comment by primetoxinz** [comment]
I'll look into this. Until then is you want the docs they are [here](https://betterwithmods.github.io/Documentation/en_us/)

**Comment by owetre18** [comment]
Thank you. I have a theory, though I'm not sure if it's correct.

Maybe my firewall or antivirus is blocking the connection to your website (through minecraft)?

**Comment by primetoxinz** [comment]
Nah, the docs are local copy in the book. Apparently it somehow didn't get put into 2.0.32. It will be back in the next release :P

**Comment by owetre18** [comment]
Alrighty, thank you!
