### ISSUE TITLE
Saw bug and feature request.

### ISSUE THREAD

**Issue by Ragestrike** [BetterWithMods/BetterWithMods#825]
First of all i was trying to rotate my saw when laying it flat with blade up so its north south but it seems to only exsit in the east west orientation. [Feature request]

The bug is, if you use a wrench to rotate the saw, it cuts up the axle.  however the blade keeps working lol.

**Comment by primetoxinz** [comment]
I fixed the power state not being updated on rotation. Though I really cannot add your feature request due to a limitation of the game in that the saw block already uses up all the meta data that it can, sorry.
