### ISSUE TITLE
Better with Mods Manual

### ISSUE THREAD

**Issue by jtpattie** [BetterWithMods/BetterWithMods#829]
NO index or documents not found

**Comment by phrit** [comment]
I'm getting the same issue, in sevtech version.  error is "document not found: en_us/index.md"

**Comment by MrHrulgin** [comment]
I'm having this issue as well on SevTech 3.0.4. It looks like it's using BWM 1.12-2.0.32.

**Comment by primetoxinz** [comment]
This was fixed in 2.0.33, until there you can view the docs at the website https://betterwithmods.github.io/Documentation/en_us/
