### ISSUE TITLE
Biomeoplenty compatibility is missing texture

### ISSUE THREAD

**Issue by collwee** [BetterWithMods/BetterWithMods#844]
biomeoplenty variant of the wood siding, wood moulding and wood corners have pink and black missing textures

**Comment by primetoxinz** [comment]
This is a known issue that is technically now resolved. In 2.1.0, which will be released today, I have replaced the sidings, mouldings and corners (MiniBlocks as they are known) with dynamically generated ones that support many more block types without any extra code.
