### ISSUE TITLE
crash with bwm 1.2.0

### ISSUE THREAD

**Issue by collwee** [BetterWithMods/BetterWithMods#845]
dos someone have a idea what is the cause here the crash log  https://paste.ee/p/LT53P

**Comment by primetoxinz** [comment]
Is BWM the only mod you updated? I cannot reproduce this and it is a very bizarre issue where something integral to the game is missing.

**Comment by collwee** [comment]
i have update forge to the latest 2654 i have downgraded back to my previous version 2613 but now craftweaker2 is crashing https://paste.ee/p/HtD2I

**Comment by collwee** [comment]
the first crash log happen on forge 2642 and up but on 2641 and down i get the crash between craftweaker2 and better with mods

**Comment by primetoxinz** [comment]
The crafttweaker crash is actually modtweaker, of which the dev is working on the update and it will hopefully be out soon.

**Comment by DaedalusGame** [comment]
try without Little Tiles on forge 2642 and up

**Comment by collwee** [comment]
i removed litle tile then it was another mod crashing i decided to stay on 2641 but now it is betterwithengineering that crashes https://github.com/BetterWithMods/BetterWithEngineering/issues/9
