### ISSUE TITLE
Many bad links in documentation

### ISSUE THREAD

**Issue by tofof** [BetterWithMods/BetterWithMods#847]
For example, [crash course](https://betterwithmods.github.io/Documentation/en_us/crashcourse/) links to the turntable at [this page](https://betterwithmods.github.io/Documentation/en_us/crashcourse/..blocks/turntable.md)
rather than the [correct place](https://betterwithmods.github.io/Documentation/en_us/blocks/turntable.md) because of a missing slash in a relative path.

Similarly, the image for the stoked cauldron (betterwithmods:docs/imgs/stoking.png) is not html, nor is the basic windmill setup (betterwithmods:docs/imgs/mechanical-power.png). Same with the kilns image (betterwithmods:docs/imgs/kilns.png).

The link to the [light block](https://betterwithmods.github.io/Documentation/en_us/blocks/light_block.md) is broken.

That's all just on that one page!

You have similar issues throughout the documentation, like the image at the top of the [cauldron page](https://betterwithmods.github.io/Documentation/en_us/blocks/cauldron.html), etc.

**Comment by primetoxinz** [comment]
Fixed in 2.1.2

**Comment by tofof** [comment]
Image at top of cauldron page, mentioned in OP - still busted.

Image at top of light block, block dispenser, block detector, buddy block, hibachi, lens block, light block, wind chime, hand crank, gearbox (and broken gearbox), wooden axle, millstone, saw, filtered hopper (and all filters on that page), bellows, mechanical booster rail, turntable, screwpump, soulforged steel, infernal enchanter, refined tools, plate armor, blasting oil, tanned leather, soap........... and so forth - all busted.

Pulley - blank page.

Crash course still has many non-links, viz.
"Tallow can be used for making [Candles], [Blasting Oil], and finally, [Soap]." 
"It’s other big use is producing White Cobble from Endstone. This is one key link for making [Soulforged Steel]; It produces the Ender Slag required for producing [Soul Flux]."
"The creation of [Soulforged Steel], the most important lategame material by far."
