### ISSUE TITLE
Rope bridge stack check, off-by-one error, poor documentation

### ISSUE THREAD

**Issue by tofof** [BetterWithMods/BetterWithMods#848]
1) Only one stack is checked
If you are attempting to span an 7-block gap with rope bridge and have, say, 10 stacks of 6 rope each, a rope will not connect despite having enough rope in your inventory.

2) Off-by-one error
2a) If you If you attempt to span a 7-block gap with rope already tied to each fencepost using a stack of 8 rope, 7 are consumed and 1 is left behind (as expected).
2b) However, using a stack of 7 rope to span the same gap -- rope will not connect despite having enough rope and it being all in one stack.

3) No error
No error is given (contrast with e.g. the windmill and waterwheel that give their requirements when failing) when rope fails to connect. For consistency, please consider adding something to the effect of "no suitable post within 10 tiles at same height was found" 

4) Bad documentation
The documentation fails to mention that the maximum span of a rope bridge is a gap of 8 blocks between fence posts (making the rope bridge basically worthless except to span the most trivial of streams). 

5) Really, 8 blocks only?
Please consider increasing the distance to, say, 64 or making the maximum span a config variable.

It's sad when you want to use a mod's features and then get disappointed that they don't work.

**Comment by primetoxinz** [comment]
I'm pretty sure Rope Bridges are actually from [Better With Addons](https://github.com/DaedalusGame/BetterWithAddons/issues)

**Comment by tofof** [comment]
Ok, my mistake. The rope is from Better With Mods and the manual describing them is named "Better With Mods Manual", though I do see that they're in the 'Better With Addons' subsection of that book.
