### ISSUE TITLE
No such static member in mods.betterwithmods.Cauldron: removeAll

### ISSUE THREAD

**Issue by WrongWeekend** [BetterWithMods/BetterWithMods#853]
Using the ModTweaker scripts provided in the CraftTweaker site:

mods.betterwithmods.Cauldron.removeAll();

mods.betterwithmods.Crucible.removeAll();

mods.betterwithmods.Kiln.removeAll();

mods.betterwithmods.Saw.removeAll();

for BWM to remove all recipes does not work, instead displaying the title message in chat (but for its respective device)

**Comment by primetoxinz** [comment]
This is fixed in the next Modtweaker update.
