### ISSUE TITLE
Saw not working correctly

### ISSUE THREAD

**Issue by lightlike** [BetterWithMods/BetterWithMods#854]
MC: 1.12.2
Forge: 14.23.2.2651
BWM: 2.1.4
Addons: Better With Addons (0.36), Better With Engineering (1.6)

Behaviour:
- Saw not dropping Products (Planks, Bark, Saw Dust, Cut Planks)
- Saw not cutting Logs above when placed face up (planks and damage still done, but also no products)

Tested with: Oak Log/Plank

**Comment by primetoxinz** [comment]
Fixed in next release (2.1.5) will be available later today.
