### ISSUE TITLE
Add config option for food dropping

### ISSUE THREAD

**Issue by owetre18** [BetterWithMods/BetterWithMods#856]
Food items won't drop when I die. It appears to be either your mod alone or how your mod interacts with one of my other mods. I don't see a config option for this. If you could add one, that would be amazing. Thank you for your time.

**Comment by primetoxinz** [comment]
Food items dropping? what?

**Comment by owetre18** [comment]
Strangely, food won't drop from my character when I die when your mod is installed. I've heard on the modpack dev Discord that this is not supposed to be the case.

**Comment by primetoxinz** [comment]
Are you absolutely positive this only happens with BWM? I have no knowledge of something that would cause such a thing. If you are sure, try disabling the Hardcore Module to see if it stops happening, it will help a narrow down the cause.

**Comment by owetre18** [comment]
I'm almost 100% certain it's BWM. I've removed the mod, killed myself, and found food on the floor where I died. I added it back, killed myself with the same food in my inventory, and it's gone.

With a default config, I drop no food (except mystery meat).

With the Hardcore module turned off, I do drop food (in addition to mystery meat).

So it seems it's something in the Hardcore module. Which is unfortunate, because it's the main reason I'm using your mod in my pack.

**Comment by primetoxinz** [comment]
Hmm, ok. I will look more into this when I get the chance. Knowing that it is at least the Hardcore section helps narrow it down. Do you have Applecore installed and have the HCHunger feature enabled?

**Comment by owetre18** [comment]
I have Applecore installed, but HCHunger turned off (in favor of Hunger Overhaul's hunger management).

**Comment by primetoxinz** [comment]
hmm, truly unsure. I will try to reproduce it in the morning.

**Comment by owetre18** [comment]
![mod list 2018-4-8](https://user-images.githubusercontent.com/5685621/38475719-ebd49b66-3b77-11e8-9868-665f57f20143.PNG)
Here's a full mod list if you need/want it. For testing purposes.

**Comment by primetoxinz** [comment]
I have found it! It was HCSeeds code to stop zombies from dropping potatoes and carrots. This code was accidentally not checking for if the drops came from a zombie. This is fixed and now configurable if you want it off still

**Comment by owetre18** [comment]
Awesome! Thanks!
