### ISSUE TITLE
Crash when walking on or using filtered hoppers to collect hemp fibers (BWM 2.1.5)

### ISSUE THREAD

**Issue by ate0ate** [BetterWithMods/BetterWithMods#857]
I placed down a filtered hopper with nothing in it, jumped up to get a look inside since it was the first time I made one and crash..
https://pastebin.com/RmDa8La7
Using forge 14.23.2.2654 in a rather heavily modded environment. Please let me know if you need any further info at all.

**Comment by ate0ate** [comment]
I don't know if this will help at all, but I experience a similar crash when I simply placed a filtered hopper down and hemp fibers fell into it from the mill stone....
https://pastebin.com/tBpYgNse

**Comment by primetoxinz** [comment]
I will look more into this soon

**Comment by ate0ate** [comment]
No problem at all. I was not trying to pester, just trying to provide any further info that I could. Thank you.

**Comment by ate0ate** [comment]
This appears to be fixed in dev, shall I close the issue?
