### ISSUE TITLE
Hi reporting as book requested in SevTech Ages

### ISSUE THREAD

**Issue by LightDefiant** [BetterWithMods/BetterWithMods#859]
The book told me to repot to this link when opening the Better with Mods Manuel.

Let me know what info you need. Screenshot attached.
![screen shot 2018-04-10 at 3 56 45 pm](https://user-images.githubusercontent.com/21005064/38592487-0c83eba8-3cd8-11e8-92f3-405998ea88d5.png)
![screen shot 2018-04-10 at 3 59 55 pm](https://user-images.githubusercontent.com/21005064/38592531-4b53d5dc-3cd8-11e8-9505-248f77a7bbfd.png)

**Comment by LightDefiant** [comment]
Just wondering what that was supposed to say, if problem is im plaing on mac I can figure the rest out myself.

**Comment by primetoxinz** [comment]
What version of SevTech?

Also @DaedalusGame

**Comment by LightDefiant** [comment]
Apologies SevTech 3.0.4 
BWM 0.3.4

**Comment by primetoxinz** [comment]
The document not found is fixed in later versions of SevTech. The issue with that one page is an bug in Better With Addons, not Better With Mods
