### ISSUE TITLE
Still issues with documentation

### ISSUE THREAD

**Issue by tofof** [BetterWithMods/BetterWithMods#862]
Reposted from #847 since no acknowledgement after a week:

Image at top of cauldron page, mentioned in OP - still busted.

Image at top of light block, block dispenser, block detector, buddy block, hibachi, lens block, light block, wind chime, hand crank, gearbox (and broken gearbox), wooden axle, millstone, saw, filtered hopper (and all filters on that page), bellows, mechanical booster rail, turntable, screwpump, soulforged steel, infernal enchanter, refined tools, plate armor, blasting oil, tanned leather, soap........... and so forth - all busted.

Pulley (not in the 'todo' section) - blank page.

Crash course still has many non-links, viz.
"Tallow can be used for making [Candles], [Blasting Oil], and finally, [Soap]."
"It’s other big use is producing White Cobble from Endstone. This is one key link for making [Soulforged Steel]; It produces the Ender Slag required for producing [Soul Flux]."
"The creation of [Soulforged Steel], the most important lategame material by far."

**Comment by primetoxinz** [comment]
My bad, I didn't see the comment on the closed issue. 
Are you not seeing the images on the website or in the book?

**Comment by tofof** [comment]
Website is where the images are broken.

**Comment by primetoxinz** [comment]
Ah yes, that is not an issue. The items are not intended to show on the site, as it is simply rendering the item as if it were in an inventory not as a separate image.

**Comment by primetoxinz** [comment]
Fixed most of the missing links, the rest is not a bug
