### ISSUE TITLE
The sidings is not availliable for all plankWood in the game...

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#863]
With the new way of importing the texture of the whole ore: plankWood, a lot of new Wooden Siding model is available, but it still lacks several, some of the most important, of course! For example, not all Natura boards are available, even though they are part of the plankWood oredict.

All Natura plankWood can be use to make is own doors, and, I realy like the fact of needed Siding to craft Doors.

I would see 2 possible solutions to solve the problem;
1- Delay the execution of the selection of all plankWood, to recover those save later during the loading (If possible after loading CraftTweaker script)
2- Give the possibility to manually add a list of blocks that will be used to make Sidings.

Thank's
Fireztonez

**Comment by primetoxinz** [comment]
You can add blocks manually.

**Comment by Fireztonez** [comment]
So, thank-you very much I will test that tomorrow probably!!
But, now is time to stop reading my things

But now it's time to stop reading my thoughts ... This is not cool guys !!

FeelsBadMan
![image](https://user-images.githubusercontent.com/19277301/38716565-4d88a5de-3eaf-11e8-97d1-904987818f07.png)

Fireztonez

**Comment by Fireztonez** [comment]
Oki,
Thank's for that information, so taht use an automatic Metadata wildcard! That's good to know...

**Comment by Fireztonez** [comment]
I can't get the IronWood Plank by Primal Core work with that option. Do you think is possible that the problem is the fact I allready have IronWood by Rustic in the sidings list and the name is basically the same?
On that case, the problem problem is, I don't want the one from rustic, because I disable the generation of that tree in the world, but that one is automatically added by BWM... And the texture from the mod is completly different, so make a recipe from Primal Core IronWood Plank to rustic IronWood siding doesn't make any sens... (Primal Core the plank is practically black and Rustic is a pale wood...)

**Comment by primetoxinz** [comment]
If your attempts to register the primal core planks manually have failed, the block likely does not meet one of our required conditions, meaning it has some specifical property to it what could make it work oddly as a MiniBlock.
I'll look into a way that will allow more control over the exact blocks that get registered.

**Comment by Fireztonez** [comment]
Oki, thank's for that information!

Yeah, I see that, primal core is not open source, this is so bad, I am a big fan of open source.... But, I just can't remove that mod from my modpack for that reason...
