### ISSUE TITLE
[Request] Possibility to put more than one Mini-Block by block space

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#864]
Hello,
I wonder if is possible to make it possible to place multiple Mini-Block in a block place, like is possible to place 2 slab 1 over the other one in Minecraft, Possibly the possibility to use for better decoration or using by example using molding to make stairs in world direcly...

Other thing should be cool, is, if is possible to place 2 different model Mini-Block in the same area (Example Jungle wood and Dark Oak), not like slabs how need to be the same model to can place 2 in the same area (Sure, that will be great if a mod can change that, to be possible to combine 2 different slab type, but that another story!)...

Fireztonez

**Comment by DaedalusGame** [comment]
errrrrr this is best reserved for a real multiblock api thingy

**Comment by Fireztonez** [comment]
Yeah, ok, I can understand and for sure this is not a real multiblock API thingy, but, this is hard to made the fact to can place 2 oak corner by example in one block space? If is something can be made easely, that should be a great thing, but if is to complicated, that's ok!

**Comment by primetoxinz** [comment]
This is rather complicated, I do intended to look more into it at some point but for now it is on the backburn
