### ISSUE TITLE
Removing Cauldron recipies using the new Methods doesn't removed Stoked Cauldron recipies

### ISSUE THREAD

**Issue by Jandakast** [BetterWithMods/BetterWithMods#868]
Trying to convert scripts away from the mods.betterwithmods.StokedCauldron method since it is being depreciated and running into an issue. 

mods.betterwithmods.Cauldron.remove([<betterwithmods:material:12>]); doesn't appear to remove the Stoked Cauldron recipes. The Vanilla Leather and BWM Tanned Leather armor pieces still convert to Glue with a stoked cauldron. Not getting any script errors. 

Is there a removeStoked and removeUnstoked method to mirror the addStoked and addUnstoked functionality? 

If not could we get one for the Cauldron and Crucible?

Just in case this is a Config option issue. 
https://gist.github.com/Jandakast/5ba72008ed705d3b2eff0338688f5431

**Comment by primetoxinz** [comment]
You should not need a specific remove function, as the recipes are contained in the same list now. Can you try specifying the item count for the glue that is output by each recipe? 
for instance `mods.betterwithmods.Cauldron.remove([ <betterwithmods:material:12>*4 ]);` should remove the leather chest glue recipe

**Comment by Jandakast** [comment]
Ah, so I need to remove them by each of the possible output amounts not just by the output item. This makes more sense and is obvious based on the documentation now that you've pointed it out. Just tested and it is working as expected. Thank you for the quick reply.
