### ISSUE TITLE
Not all BWM recipies converted to use the new miniBlocks

### ISSUE THREAD

**Issue by Jandakast** [BetterWithMods/BetterWithMods#871]
The deprecated Stone Siding is still used in the Redstone Comparator. 

The deprecated Dark Oak Wood Siding is still used in making Dark Oak Fence Gate if high efficiency crafting option is enabled. 

Forge 2666
BetterWithMods-1.12-2.1.7

**Comment by primetoxinz** [comment]
Fixed :)

**Comment by Jandakast** [comment]
:)
