### ISSUE TITLE
HC Buckets prevents non-vanilla water buckets from filling some containers

### ISSUE THREAD

**Issue by WrongWeekend** [BetterWithMods/BetterWithMods#873]
With the HC Buckets option enabled, trying to use a filled water bucket from a mod (I tried MMD Buckets and Ceramics' clay bucket) causes a flowing block to be placed on top of or beside the container. Sometimes water is added to the container at the same time, depending on the container.

**Comment by primetoxinz** [comment]
Fixed in dev.
