### ISSUE TITLE
Well buckets in deep water can't be retrieved

### ISSUE THREAD

**Issue by stohun01** [BetterWithMods/BetterWithMods#884]
Using a well bucket in water deeper than 1 block will break the rope block above it needed to pull the bucket back up. It should probably stop at the surface.

**Comment by primetoxinz** [comment]
So, I was going to fix this when I originally saw it. I looked into it more I decided it is a feature. The pulley has no way to know it is entering water, so it shouldn't simply stop. The solution is to properly count the amount of rope your pulley needs to lose the bucket.
