### ISSUE TITLE
[CraftTweaker Java Error] Recipe with Miniblock function crash and cause Java error

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#890]
I Pprobably have an error in my script, but the fact of the error return an Java error is not normal I think, so I report to you the Crafttweaker logs

https://gist.github.com/Fireztonez/5ff3a0b98e1e1ee1bbe0df3222eecd4b

BWM: 1.12.2-1.12
BWA: 0.40
Forge: 2669

Tell me if you need something else

Fireztonez

**Comment by DaedalusGame** [comment]
https://github.com/CraftTweaker/CraftTweaker/issues

**Comment by bookerthegeek** [comment]
Also....
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[90:crafttweaker]: vanilla.zs}: Truncated class file
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[80:crafttweaker]: bwm.zs}
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: BetterWithMods\saw.zs}: Bad type on operand stack
```
This tells me that the files ```vanilla.zs```, ```bwm.zs``` & ```saw.zs``` all have errors in them. Disable all recipes in those scripts, and then enable them one at a time until you get an error. I can promise you that you have them written incorrectly. 

Also when reporting script errors, it helps to also you know post the scripts?

**Comment by Fireztonez** [comment]
I found the problem I think... The problem comes from global call in those file, but the content not correspond at what I want to use at the first time...
The problem come from the fact I change the definition after I discover the Miniblock function, but I use one of that global in saw.zs. So the fact of vanilla.zs, saw.zs and bwm.zs depend each one from _global.siding.zs... So I will just change my script...

This is my bad for the error. After I don't know if there a way to avoid the java error.

**Comment by primetoxinz** [comment]
Resolved in discord
