### ISSUE TITLE
[Feature Request] Config option to turn off automatic fuel combustion in furnaces

### ISSUE THREAD

**Issue by Davoleo** [BetterWithMods/BetterWithMods#891]
The title says it all

Forge version: 2673
BetterWithMods version: 2.1.12

![image](https://user-images.githubusercontent.com/24458276/39399208-304de34a-4b1a-11e8-9faf-08fc24e4b43a.png)

**Comment by DaedalusGame** [comment]
Done
[Try this when it finishes building](https://ci.blamejared.com/job/BetterWithMods/507/)

**Comment by Davoleo** [comment]
wow, thanks for the quick answer and the even quicker implementation!
