### ISSUE TITLE
Refined tools can receive any enchantment from Vanilla Enchanting Table.

### ISSUE THREAD

**Issue by jrdroney** [BetterWithMods/BetterWithMods#893]
It's all in the name basically. Putting a refined sword/battleaxe/mattock/etc into a Vanilla enchanting table with "B:"Steel Requires Infernal Enchanter"=false" in the config, and it'll get basically any enchantment. I've seen it get Protection, Lure, you name it. Often multiple different types at once. For example, I have a sword with Smite 4 and Fire Protection 2.

**Comment by primetoxinz** [comment]
Fixed in next release
