### ISSUE TITLE
[Suggestion] add smelt time to JEI for hcfurnace values

### ISSUE THREAD

**Issue by stohun01** [BetterWithMods/BetterWithMods#896]
There's no way of knowing in game how long the tweaked Furnace Timing Recipes will take. I suggest adding "Smelt Time: x" under the output of the effected items in the Smelting tab of JEI.

**Comment by primetoxinz** [comment]
So it isn't really feasible to add more information to the JEI section for furnaces, so I instead just made it a tooltip on the item.
