### ISSUE TITLE
Unable to place waterwheel

### ISSUE THREAD

**Issue by bondenn** [BetterWithMods/BetterWithMods#902]
Forge Version: 14.23.3.2678

**Reproduction Steps:**

1. Place two gearboxes and axles as in [this picture](https://i.imgur.com/YEwAR6M.png).
2. Try to place waterwheels on the axles
3. The first waterwheel will block the placement of the second, saying there's not enough room

EDIT: Seems like no other waterwheel can be placed within a 5x5 area centered on the first waterwheel unless it's on the same X or Z axis

**Comment by primetoxinz** [comment]
Fixed in dev.
