### ISSUE TITLE
Recursive crafting?

### ISSUE THREAD

**Issue by Davoleo** [BetterWithMods/BetterWithMods#905]
Ok, I found that to make windmill sails you need to use a saw which needs continuous mechanical energy, which you can't make before having a windmill/waterwheel

I don't know if i'm missing something, but it seems not craftable

**Comment by Davoleo** [comment]
it seems the same with crafting axles and water wheels

**Comment by DaedalusGame** [comment]
axles can either be planks + rope or moulding + rope
windmill sails can either be slabs + fabric or siding + fabric (this one I should change sometime, as it's supposed to be moulding or planks)
watermill correctly requires glue and sidings making it a post-saw endeavor

**Comment by Davoleo** [comment]
mmh, ok thanks! closing this issue
