### ISSUE TITLE
(1.12.2)Document not found: en_us/index.md...

### ISSUE THREAD

**Issue by ate0ate** [BetterWithMods/BetterWithMods#907]
First off, I apologize if this is a duplicate in any way as I see this has been mentioned here before several times. The only reason I even bring it up is that after perusing the closed issues I couldn't figure out if the issue is fixed or not, or caused by BWMods itself or BWAddons as there is no mention of it anywhere on that repository. 

I have been getting the "Document not found: en_us/index.md" message in the BWM manual for quite a long time now and through quite a few versions of BWM. BWA's information displays just fine, only BWM does not display. Currently this happens using BWM 2.1.12 and BWA 0.40hotfix with the recommended forge (2655) or the latest (2678). I am using a private custom pack not too dissimilar from most other kitchen-sink packs, if that matters in any way.

As an aside, I attempted to compile the current BWM 1.12 branch since there's been some commits made mentioning improvments to documentation implementation but compile fails as commit aaca0fdccb718c832d23d4bbb1c37c8f76ba1744 edits src/main/java/betterwithmods/manual/api/manual/ContentProvider.java deleting the import for "betterwithmods.manual.api.prefab.manual.ResourceContentProvider" and tries to import "betterwithmods.manual.client.manual.provider.ResourceContentProvider" instead but cannot as that is later deleted entirely in the same commit. 

Clearly I'm not a coder by any means, but reverting that single change or just deleting the bad import allowed me to compile without issue, but did nothing for the "Document not found" issue. As I said, I have no clue how to code so I'm sure my attempts at fixing my problem look completely retarded to anyone with even an iota of modding knowledge, but I tried lol. Thanks for your time.

**Comment by primetoxinz** [comment]
I am making a release momentarily that should have this fixed. I will confirm before I put it on curse

**Comment by primetoxinz** [comment]
Confirmed. 2.1.13 will be curse soon :)
