### ISSUE TITLE
Turntable cause crash

### ISSUE THREAD

**Issue by xinyuan-liu** [BetterWithMods/BetterWithMods#910]
![crash](https://user-images.githubusercontent.com/17433503/39749394-25ff3d3a-52e5-11e8-8d53-1c99d6394162.png)
Such a structure will cause the game crashing.
This bug still exists after upgrading the mod to 2.1.14.
The crash report :
[crash-2018-05-08_16.35.40-server.txt](https://github.com/BetterWithMods/BetterWithMods/files/1983243/crash-2018-05-08_16.35.40-server.txt)

**Comment by xinyuan-liu** [comment]
This bug does not exists in 2.0.34.

**Comment by primetoxinz** [comment]
Fixed in dev.
