### ISSUE TITLE
Planters lose their held block upon reload.

### ISSUE THREAD

**Issue by tyranno66** [BetterWithMods/BetterWithMods#913]
Encountered this issue while playing SevTech. I decided to make my rustic setup prettier by using planters yet when I travel between dimensions the dirt block in them fails to render unless there's a block update and on leaving and reopening the instance the dirt block with the plants planted on top of it disappear.

**Comment by primetoxinz** [comment]
Fixed in BWM 2.1.0 and greater, which i now in sevtech 3.0.7
