### ISSUE TITLE
Newlines in language files not working as intended

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [BetterWithMods/BetterWithMods#918]
https://github.com/BetterWithMods/BetterWithMods/blob/63ec5dfee8e6e96df2b9d918c063b5484a096c23/src/main/resources/assets/betterwithmods/lang/en_US.lang#L545

There is also another line that is affected. When displayed, the raw escape sequences are shown.

The default language format does not support `\n` for newlines. The way to achieve multiline values is using `#PARSE_ESCAPES`. Be aware that if you were to enable this, keys containing colon characters will break because of how the properties file format works.

Documentation for this behavior can be found in [this pending Forge RTD PR](https://github.com/MinecraftForge/Documentation/pull/165/files).

**Comment by primetoxinz** [comment]
Thanks for the info but I'm not too worried about having newlines. I'll just remove them.

**Comment by JamiesWhiteShirt** [comment]
You might want to do the same with your other languages, too.

**Comment by primetoxinz** [comment]
:+1:
