### ISSUE TITLE
Can't see the betterwithmods part in the book.

### ISSUE THREAD

**Issue by Pixelmnkey** [BetterWithMods/BetterWithMods#925]
Like the title says, playing the last sevtech version and if I open the manual, it only shows the better with addons part, not the rest, also why does my millstone sound like it's playing rly bad the flute when milling netherrack?

**Comment by primetoxinz** [comment]
known bug in Sevtech.
The intent behind the noise to give incentive to build your base spread out, rather than crammed together, to avoid unwanted noise polition.

**Comment by DaedalusGame** [comment]
netherrack contains the souls of the damned, tis but normalcy

**Comment by Pixelmnkey** [comment]
You can just place a muffler besides it, it's annoying lol.

**Comment by primetoxinz** [comment]
Our mod is not designed with a cheating block in mind, if you don't like it feel free to use that muffler. Otherwise it is not an issue.

**Comment by Pixelmnkey** [comment]
Cheating block? My base is spread out and still hearing the flute sound every time I grind netherrack is annoying af.

**Comment by primetoxinz** [comment]
It's supposed to be annoying.
