### ISSUE TITLE
[Null Pointer] Exception ticking world

### ISSUE THREAD

**Issue by artdude543** [BetterWithMods/BetterWithMods#928]
Hello!

We had a report of a Null Pointer from world ticking, linked issue: https://github.com/DarkPacks/SevTech-Ages/issues/2456

Crash Report: https://pastebin.com/HFfs9FeK

Version: 2.1.15

If you guys could look into it that would be awesome!

Thanks

**Comment by DaedalusGame** [comment]
`return this.skyLight.get(x, y, z);` this line in vanilla code crashes. As we don't reflect into ExtendedBlockStorage skyLight should never be null. Even if we did, skyLight should never be null. I have 0 idea what in our mod would cause that but I will enquiry about this bizarre bug on MMD.

**Comment by DaedalusGame** [comment]
ok I have found the issue, this is el legacy code from one thousand years past and it was improperly updated to a newer mapping.
