### ISSUE TITLE
Dispenser deletes mini blocks instead of placing or dropping the item 

### ISSUE THREAD

**Issue by Jandakast** [BetterWithMods/BetterWithMods#938]
This was originally reported on the SevTech Ages issue tracker. If you put Siding, moulding, or corners in a vanilla minecraft dispenser or cyclic block placer the items are deleted when you supply a redstone signal. 

https://github.com/DarkPacks/SevTech-Ages/issues/2538

**Comment by primetoxinz** [comment]
This is quark's fault

**Comment by DaedalusGame** [comment]
i bet this is reproducible if you put a chisels and bits thing in a block placer?

**Comment by primetoxinz** [comment]
The two mods do not properly implement placement through ItemBlock, instead they try to place the block state manually, this is not our fault in any means.
