### ISSUE TITLE
Technical issue: world.setBlockState(...) when using micro blocks returns 'true' but fails to place in world causing item loss with automated machines that place in world

### ISSUE THREAD

**Issue by PrinceOfAmber** [BetterWithMods/BetterWithMods#940]
For reference
https://github.com/PrinceOfAmber/Cyclic/issues/812
https://github.com/DarkPacks/SevTech-Ages/issues/2538

Basically, I call the standard function
` success = world.setBlockState(placePos, placeState, 3);`

in my tile entity on the server side when placing blocks in world.  If i get success == true, then I decrement the item stack.

However, i am getting a TRUE response even when these micro blocks do not get placed.  My expected result is either

1. it gets placed in world
2. it returns false

Block is {betterwithmods:corner_wood} metadata 0
When i write blockstate to string the state says ' betterwithmods:corner_wood'

Reference in my code 
https://github.com/PrinceOfAmber/Cyclic/blob/6c8a7a51e2204f8879a35a4e3158665f3e5772ba/src/main/java/com/lothrazar/cyclicmagic/core/util/UtilPlaceBlocks.java#L119

I am guessing this has something to do with setBlockState not having a player context, and usually you have that player overlay outline to detect what orientation to place, but a "false" return would be ideal.

**Comment by DaedalusGame** [comment]
you need to actually place the block using the itemblock, not just flat call setBlockState, miniblocks have nbt that needs to be resolved to place correctly. See #938

**Comment by primetoxinz** [comment]
Yeah, you cannot use setBlockState for mini blocks as the tile entity also have to be initialized through the custom ItemBlock. You should be doing something similar to [this code from our block placer](https://github.com/BetterWithMods/BetterWithMods/blob/1.12/src/main/java/betterwithmods/common/blocks/behaviors/BehaviorDefaultDispenseBlock.java#L48-L61)

**Comment by PrinceOfAmber** [comment]
oh thanks! I didnt think of the itemblock
