### ISSUE TITLE
Server crash on startup with last Thaumcraft version

### ISSUE THREAD

**Issue by Bulldog83** [BetterWithMods/BetterWithMods#945]
Minecraft 1.12.2
Forge 14.23.3.2673
BWM 2.1.20
Thaumcraft 6.1.BETA14

https://gist.github.com/Bulldog83/1f8741414ba009fca4e0d9fcfab324c3

**Comment by primetoxinz** [comment]
for now disable the Thaumcraft compat module until I can fix the support
