### ISSUE TITLE
Crash with Thaumcraft-1.12.2-6.1.BETA14

### ISSUE THREAD

**Issue by KingCactaur** [BetterWithMods/BetterWithMods#951]
Forge Version: 14.23.3.2702

Mods involved:
Thaumcraft 6 (Thaumcraft-1.12.2-6.1.BETA14.jar)

How to reproduce:
Happened while loading

Crash Report: https://pastebin.com/aekiWKkU

**Comment by KingCactaur** [comment]
Now that I look at this it might be a thaumcraft issue, I'll post it there too.

**Comment by primetoxinz** [comment]
It's not a TC bug

**Comment by primetoxinz** [comment]
I have fixed this in dev already

**Comment by primetoxinz** [comment]
Uploaded the fix for this to curse

**Comment by KingCactaur** [comment]
Thank you very much! Keep up the good work!
