### ISSUE TITLE
[No Class Def] Server Crash

### ISSUE THREAD

**Issue by artdude543** [BetterWithMods/BetterWithMods#953]
Hello!

We had a report of a NoClassDefFoundError, linked issue: https://github.com/DarkPacks/SevTech-Ages/issues/2634

I'm not sure how this one happened as really this would of been found ages ago. I can only assume they have enabled a module we don't allow. Or the configs are broken and then regen enabled a module which has the bug in it.

But this may of already been fixed with your latest commits/changes. But no harm in double checking :)

Crash Report: https://pastebin.com/KrDeYGgc

Version: 2.1.15

If you guys could look into it that would be awesome!

Thanks

**Comment by primetoxinz** [comment]
Yeah this was a crash with HCFurance which is disabled in sevtech. Has been fixed for a couple versions
