### ISSUE TITLE
modtweaker script FilteredHopper.removeAll(); crash game

### ISSUE THREAD

**Issue by ilvrak** [BetterWithMods/BetterWithMods#967]
after BWM version 2.1.20 (21,22)
modtweaker script string
`mods.betterwithmods.FilteredHopper.removeAll();`
crashes minecraft on loading

only this, other "removealls" works fine

**Comment by primetoxinz** [comment]
Need the crash log

**Comment by ilvrak** [comment]
https://pastebin.com/fWiXrSmX

**Comment by primetoxinz** [comment]
@DaedalusGame ?

**Comment by DaedalusGame** [comment]
my name jeff and why you do this to me

**Comment by Madxmike** [comment]
This is being caused by 
https://github.com/BetterWithMods/BetterWithMods/commit/8252435127f4cdafbcbaba1bdb4d971108248c4b#diff-c0968582b03382828090d146bbb9f364L28

Changing List<HopperRecipe> back to ArrayList<HopperRecipe> fixes the issue.
