### ISSUE TITLE
[Request] Industrial Hemp harvested by Reed Farm

### ISSUE THREAD

**Issue by klomer** [BetterWithMods/BetterWithMods#972]
Immerssive Engineering’s hemp is currently not harvested by the reed farm. Hemp is grows similar to reeds, in that you are only supposed to chop the top of the plant to get seeds/hemp.  

Can you add support for it in the Reed Farm?

(This is for Ancient Warfare 2)

**Comment by primetoxinz** [comment]
huh? did you mean this to be for forestry?

**Comment by primetoxinz** [comment]
Well that isn't up to me to add Immersive Engineering compat for another mod. Better With Mods adds its own hemp that can already by harvested by the Ancient Warfare 2 Crop Farm

**Comment by klomer** [comment]
Could you make the reed farm treat all plants inside it like reed/cactus, etc?  Regardless of origin?

**Comment by primetoxinz** [comment]
It is not my mod, go ask the Ancient Warfare devs

**Comment by klomer** [comment]
Oh, sorry!  Thanks!
